# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: enumerator_io_reader 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "enumerator_io_reader"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Fonsan"]
  s.date = "2015-07-14"
  s.description = "Read a byte stream from your enumerable"
  s.files       = ["lib/enumerator/io/reader.rb"]
  s.email = "fonsan@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.homepage = "http://github.com/Fonsan/enumerator_io_reader"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "Treat your enumerators as readable IO streams"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

